config/routes.rb
Rails.application.routes.draw do
  root to: 'bids#index'
  
  resources :granites

  resources :cabinets

  resources :bids

end

app/models/granite.rb
class Granite < ActiveRecord::Base
  has_many :bids
  mount_uploader :image, ImageUploader
end

app/controllers/granites_controller.rb
class GranitesController < ApplicationController
  before_action :set_granite, only: [:show, :edit, :update, :destroy]

  # GET /granites
  # GET /granites.json
  def index
    @granites = Granite.all
  end

  # GET /granites/1
  # GET /granites/1.json
  def show
  end

  # GET /granites/new
  def new
    @granite = Granite.new
  end

  # GET /granites/1/edit
  def edit
  end

  # POST /granites
  # POST /granites.json
  def create
    @granite = Granite.new(granite_params)

    respond_to do |format|
      if @granite.save
        format.html { redirect_to @granite, notice: 'Granite was successfully created.' }
        format.json { render :show, status: :created, location: @granite }
      else
        format.html { render :new }
        format.json { render json: @granite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /granites/1
  # PATCH/PUT /granites/1.json
  def update
    respond_to do |format|
      if @granite.update(granite_params)
        format.html { redirect_to @granite, notice: 'Granite was successfully updated.' }
        format.json { render :show, status: :ok, location: @granite }
      else
        format.html { render :edit }
        format.json { render json: @granite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /granites/1
  # DELETE /granites/1.json
  def destroy
    @granite.destroy
    respond_to do |format|
      format.html { redirect_to granites_url, notice: 'Granite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_granite
      @granite = Granite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def granite_params
      params.require(:granite).permit(:name, :image)
    end
end

app/helpers/granites_helper.rb
module GranitesHelper
end

app/views/granites/_form.html.erb
<%= form_for(@granite) do |f| %>
  <% if @granite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@granite.errors.count, "error") %> prohibited this granite from being saved:</h2>

      <ul>
      <% @granite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/granites/edit.html.erb
<h1>Editing granite</h1>

<%= render 'form' %>

<%= link_to 'Show', @granite %> |
<%= link_to 'Back', granites_path %>

app/views/granites/index.html.erb
<h1>Granite Styles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @granites.each do |granite| %>
      <tr>
        <td><%= granite.name %></td>
        <td><%= image_tag(granite.image, :width => 50) if granite.image.present? %></td>
        <td><%= link_to 'Show', granite %></td>
        <td><%= link_to 'Edit', edit_granite_path(granite) %></td>
        <td><%= link_to 'Destroy', granite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Granite Style', new_granite_path %>

app/views/granites/new.html.erb
<h1>New granite</h1>

<%= render 'form' %>

<%= link_to 'Back', granites_path %>

app/views/granites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @granite.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@granite.image, :width => 200) if @granite.image.present? %>
</p>

<%= link_to 'Edit', edit_granite_path(@granite) %> |
<%= link_to 'Back', granites_path %>