config/routes.rb
Rails.application.routes.draw do
  root to: 'bids#index'
  
  resources :granites

  resources :cabinets

  resources :bids

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :cabinet
  #validates :cabinet_id, :name, presence: true  # Makes database fields required
  
  belongs_to :granite
  #validates :granite_id, :name, presence: true  # Makes database fields required
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: [:show, :edit, :update, :destroy]

  # GET /bids
  # GET /bids.json
  def index
    @bids = Bid.all
  end

  # GET /bids/1
  # GET /bids/1.json
  def show
    
    # Create the document object
    pdf = Prawn::Document.new
    
    # Draw the X and Y axis - COMMENT OUT IN PRODUCTION
    # pdf.stroke_axis
    
    # Draw the bid sheet
    # -------------------------------------------------------------------------
    # Top of the document is y = 720.0
    
    # Header
    logo_image = @bid.logo
    pdf.image "app/assets/images/" + logo_image.to_s, :at => [0, 720], :width => 70, :height => 70
    pdf.draw_text @bid.client_name, :at => [87,705], :size => 20
    pdf.draw_text @bid.project_name, :at => [87,672], :size => 30, :style => :bold
    
    # Format date
    month = @bid.date.strftime('%B')
    day = @bid.date.strftime('%d')
    year = @bid.date.strftime('%Y')
    formatted_date = month + " " + day + ", " + year
    pdf.draw_text formatted_date, :at => [88,650], :size => 10
    
    # Left column
    # -------------------------------------------------------------------------
    
    pdf.draw_text "Project Costs", :at => [0,618], :size => 18
    
    # Format currency
    cabinet_cost = format("$%.2f",@bid.cabinet_cost)  # Round cents to 2 digits & add a dollar sign
    cabinet_cost = cabinet_cost.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse  # Add a comma every 3 digits

    granite_cost = format("$%.2f",@bid.granite_cost)
    granite_cost = granite_cost.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse
    
#     tax_cost = format("$%.2f",@bid.tax_cost)
#     tax_cost = tax_cost.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse
    
    total_cost = format("$%.2f",@bid.total_cost)
    total_cost = total_cost.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse
    
    pdf.draw_text "Cabinets", :at => [0,593], :size => 14
    pdf.draw_text cabinet_cost, :at => [0,567], :size => 30
    
    # Assemble include statement for cabinets
    cabinet_includes = ""
    cabinet_includes_count = 0
    # Make a string of includes, separated by commas
    if @bid.cabinet_delivery == true
      cabinet_includes_count += 1
      cabinet_includes = "delivery, "
    end
    if @bid.cabinet_removal == true
      cabinet_includes_count += 1
      cabinet_includes = cabinet_includes + "removal, "
    end
    if @bid.cabinet_installation == true
      cabinet_includes_count += 1
      cabinet_includes = cabinet_includes + "installation, "
    end
    if @bid.cabinet_knobspulls == true
      cabinet_includes_count += 1
      cabinet_includes = cabinet_includes + "knobs/pulls, "
    end
    if @bid.cabinet_tax == true
      cabinet_includes_count += 1
      cabinet_includes = cabinet_includes + "taxes, "
    end
    # Remove the trailing comma and space
    cabinet_includes = cabinet_includes[0...-2]
    # If there are just two includes use " and " instead of a comma
    if cabinet_includes_count == 2
      cabinet_includes.gsub! ', ', ' and '
    end
    # Add the beginning and end of the sentence if there's at least one include.
    if cabinet_includes_count > 0
      cabinet_includes = "Includes " + cabinet_includes + "."
    end
    pdf.font_size 9
    pdf.bounding_box([0, 561], :width => 207, :height => 30) do
      pdf.transparent(0.0) { pdf.stroke_bounds }
      pdf.text cabinet_includes
    end
    
    pdf.draw_text "Counter Tops", :at => [0,506], :size => 14
    pdf.draw_text granite_cost, :at => [0,480], :size => 30
    
    # Assemble include statement for counter tops
    counter_includes = ""
    counter_includes_count = 0
    # Make a string of includes, separated by commas
    if @bid.granite_installation == true
      counter_includes_count += 1
      counter_includes = "installation, "
    end
    if @bid.granite_sinks == true
      counter_includes_count += 1
      counter_includes = counter_includes + "sinks, "
    end
    if @bid.granite_specialtyedge == true
      counter_includes_count += 1
      counter_includes = counter_includes + "specialty edge, "
    end
    if @bid.granite_tax == true
      counter_includes_count += 1
      counter_includes = counter_includes + "taxes, "
    end
    # Remove the trailing comma and space
    counter_includes = counter_includes[0...-2]
    # If there are just two includes use " and " instead of a comma
    if counter_includes_count == 2
      counter_includes.gsub! ', ', ' and '
    end
    # Add the beginning and end of the sentence if there's at least one include.
    if counter_includes_count > 0
      counter_includes = "Includes " + counter_includes + "."
    end
    pdf.font_size 9
    pdf.bounding_box([0, 474], :width => 207, :height => 30) do
      pdf.transparent(0.0) { pdf.stroke_bounds }
      pdf.text counter_includes
    end
    
#     pdf.draw_text "Tax", :at => [0,479], :size => 14
#     pdf.draw_text tax_cost, :at => [0,453], :size => 30
    pdf.draw_text "Total", :at => [0,422], :size => 14
    pdf.draw_text total_cost, :at => [0,396], :size => 30
    
    pdf.draw_text "Conditions & Information", :at => [0,360], :size => 18
    conditions = @bid.conditions
    pdf.font_size 9
    pdf.bounding_box([0, 340], :width => 207, :height => 290) do
      pdf.transparent(0.0) { pdf.stroke_bounds }
      pdf.text conditions
    end
    
    # Center column
    # -------------------------------------------------------------------------
    
    pdf.draw_text "Cabinet Mix", :at => [220,618], :size => 18
    pdf.draw_text "Qty", :at => [220,596], :size => 10, :style => :bold
    pdf.draw_text "SKU", :at => [250,596], :size => 10, :style => :bold
    cabinet_mix = @bid.cabinet_mix
    
    # Replace the tab copied & pasted from the spreadsheet with spaces & hyphens
    cabinet_mix = cabinet_mix.gsub! /\t/, '   --   '
    pdf.font_size 9
    pdf.bounding_box([225, 590], :width => 110, :height => 540) do
      pdf.transparent(0.0) { pdf.stroke_bounds }  # Change 0.0 to 0.5 to turn on the border
      pdf.text cabinet_mix
    end
    
    # Right column
    # -------------------------------------------------------------------------
    
    cabinet_name = @bid.cabinet.name
    pdf.draw_text cabinet_name, :at => [347,618], :size => 18
    
    # Embed the cabinet image
    cabinet_image = @bid.cabinet.image
    pdf.image "public/" + cabinet_image.to_s, :at => [347, 603], :width => 190, :height => 190
    
    cabinet_specs = @bid.cabinet.specs
    pdf.font_size 9
    pdf.bounding_box([347, 400], :width => 190, :height => 120) do
      pdf.transparent(0.0) { pdf.stroke_bounds }  # Change 0.0 to 0.5 to turn on the border
      pdf.text cabinet_specs
    end
    granite_name = @bid.granite.name
    pdf.draw_text granite_name, :at => [347,255], :size => 18
    
    # Embed the granite image
    granite_image = @bid.granite.image
    pdf.image "public/" + granite_image.to_s, :at => [347, 240], :width => 190, :height => 190
    
    # Bottom row
    # -------------------------------------------------------------------------
    
    pdf.fill_rectangle [0, 15], 120, 3
    pdf.draw_text "Signature", :at => [0,0], :size => 10
    pdf.fill_rectangle [139, 15], 120, 3
    pdf.draw_text "Full Name", :at => [139,0], :size => 10
    pdf.fill_rectangle [278, 15], 120, 3
    pdf.draw_text "Company", :at => [278,0], :size => 10
    pdf.fill_rectangle [417, 15], 120, 3
    pdf.draw_text "Date", :at => [417,0], :size => 10
    
    # Produce the PDF
    # -------------------------------------------------------------------------
    
    # Use the bid ID to name the PDF file
    pdf.render_file "public/pdfs/" + @bid.id.to_s + ".pdf"
    
  end

  # GET /bids/new
  def new
    @bid = Bid.new
  end

  # GET /bids/1/edit
  def edit
  end

  # POST /bids
  # POST /bids.json
  def create
    @bid = Bid.new(bid_params)

    respond_to do |format|
      if @bid.save
        format.html { redirect_to @bid, notice: 'Bid was successfully created.' }
        format.json { render :show, status: :created, location: @bid }
      else
        format.html { render :new }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bids/1
  # PATCH/PUT /bids/1.json
  def update
    respond_to do |format|
      if @bid.update(bid_params)
        format.html { redirect_to @bid, notice: 'Bid was successfully updated.' }
        format.json { render :show, status: :ok, location: @bid }
      else
        format.html { render :edit }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1
  # DELETE /bids/1.json
  def destroy
    @bid.destroy
    respond_to do |format|
      format.html { redirect_to bids_url, notice: 'Bid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid
      @bid = Bid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bid_params
      params.require(:bid).permit(:logo, :client_name, :project_name, :date, :cabinet_cost, :cabinet_delivery, :cabinet_removal, :cabinet_installation, :cabinet_knobspulls, :cabinet_tax, :granite_cost, :granite_tax, :granite_installation, :granite_sinks, :granite_specialtyedge, :total_cost, :conditions, :cabinet_mix, :cabinet_id, :granite_id)
    end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_form.html.erb
<%= form_for(@bid) do |f| %>
  <% if @bid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
      <% @bid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :logo %><br>
    <%# f.text_field :logo %>
    <select id="bid_logo" name="bid[logo]">
      <option value="gcs-logo.png">GC Sourcing</option>
      <option value="cc-logo.png">Cabinets & Coffee</option>
    </select>
  </div>
  <div class="field">
    <%= f.label :client_name %><br>
    <%= f.text_field :client_name %>
  </div>
  <div class="field">
    <%= f.label :project_name %><br>
    <%= f.text_field :project_name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :cabinet_cost %><br>
    <%= f.text_field :cabinet_cost %>
  </div>
  <div class="field">
    <%= f.label :cabinet_delivery %><br>
    <%= f.check_box :cabinet_delivery %>
  </div>
  <div class="field">
    <%= f.label :cabinet_removal %><br>
    <%= f.check_box :cabinet_removal %>
  </div>
  <div class="field">
    <%= f.label :cabinet_installation %><br>
    <%= f.check_box :cabinet_installation %>
  </div>
  <div class="field">
    <%= f.label :cabinet_knobspulls %><br>
    <%= f.check_box :cabinet_knobspulls %>
  </div>
  <div class="field">
    <%= f.label :cabinet_tax %><br>
    <%= f.check_box :cabinet_tax %>
  </div>
  <div class="field">
    <%= f.label :granite_cost %><br>
    <%= f.text_field :granite_cost %>
  </div>
  <div class="field">
    <%= f.label :granite_installation %><br>
    <%= f.check_box :granite_installation %>
  </div>
  <div class="field">
    <%= f.label :granite_sinks %><br>
    <%= f.check_box :granite_sinks %>
  </div>
  <div class="field">
    <%= f.label :granite_specialtyedge %><br>
    <%= f.check_box :granite_specialtyedge %>
  </div>
  <div class="field">
    <%= f.label :granite_tax %><br>
    <%= f.check_box :granite_tax %>
  </div>
  <!--<div class="field">
    <%# f.label :tax_cost %><br>
    <%# f.text_field :tax_cost %>
  </div>-->
  <div class="field">
    <%= f.label :total_cost %><br>
    <%= f.text_field :total_cost %>
  </div>
  <div class="field">
    <%= f.label :conditions %><br>
    <%= f.text_area :conditions %>
  </div>
  <div class="field">
    <%= f.label :cabinet_mix %><br>
    <%= f.text_area :cabinet_mix %>
  </div>
  <div class="field">
    <%= f.label :cabinet_id %><br>
    <%= f.collection_select :cabinet_id, Cabinet.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :granite_id %><br>
    <%= f.collection_select :granite_id, Granite.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bids/edit.html.erb
<h1>Editing bid</h1>

<%= render 'form' %>

<%= link_to 'Show', @bid %> |
<%= link_to 'Back', bids_path %>

app/views/bids/index.html.erb
<h1>Bids</h1>

<table>
  <thead>
    <tr>
      <th>Logo</th>
      <th>Client name</th>
      <th>Project name</th>
      <th>Date</th>
      <th>Cabinet cost</th>
      <th>Granite cost</th>
      <!--<th>Tax cost</th>-->
      <th>Total cost</th>
      <!--<th>Conditions</th>-->
      <!--<th>Cabinet mix</th>-->
      <th>Cabinet style</th>
      <th>Granite style</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bids.each do |bid| %>
      <tr>
        <td><%= bid.logo %></td>
        <td><%= bid.client_name %></td>
        <td><%= bid.project_name %></td>
        <td><%= bid.date %></td>
        <td><%= bid.cabinet_cost %></td>
        <td><%= bid.granite_cost %></td>
        <!--<td><%# bid.tax_cost %></td>-->
        <td><%= bid.total_cost %></td>
        <!--<td><%# bid.conditions %></td>-->
        <!--<td><%# bid.cabinet_mix %></td>-->
        <td><%= bid.cabinet.name %></td>
        <td><%= bid.granite.name %></td>
        <td><%= link_to 'Show', bid %></td>
        <td><%= link_to 'Edit', edit_bid_path(bid) %></td>
        <td><%= link_to 'Destroy', bid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bid', new_bid_path %>

app/views/bids/new.html.erb
<h1>New bid</h1>

<%= render 'form' %>

<%= link_to 'Back', bids_path %>

app/views/bids/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= @cabinet_image_path2 %>

<p><a href="/pdfs/<%= @bid.id.to_s %>.pdf">View the Bid PDF</a></p>

<p>
  <strong>Logo:</strong>
  <%= @bid.logo %>
</p>

<p>
  <strong>Client name:</strong>
  <%= @bid.client_name %>
</p>

<p>
  <strong>Project name:</strong>
  <%= @bid.project_name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @bid.date %>
</p>

<p>
  <strong>Cabinet cost:</strong>
  <%= @bid.cabinet_cost %>
</p>

<p>
  <strong>Cabinet Delivery:</strong>
  <%= @bid.cabinet_delivery %>
</p>

<p>
  <strong>Cabinet Removal:</strong>
  <%= @bid.cabinet_removal %>
</p>

<p>
  <strong>Cabinet Installation:</strong>
  <%= @bid.cabinet_installation %>
</p>

<p>
  <strong>Cabinet Knobs/Pulls:</strong>
  <%= @bid.cabinet_knobspulls %>
</p>

<p>
  <strong>Cabinet Tax:</strong>
  <%= @bid.cabinet_tax %>
</p>

<p>
  <strong>Granite cost:</strong>
  <%= @bid.granite_cost %>
</p>

<p>
  <strong>Granite Installation:</strong>
  <%= @bid.granite_installation %>
</p>

<p>
  <strong>Granite Sinks:</strong>
  <%= @bid.granite_sinks %>
</p>

<p>
  <strong>Granite Specialty Edge:</strong>
  <%= @bid.granite_specialtyedge %>
</p>

<p>
  <strong>Granite Tax:</strong>
  <%= @bid.granite_tax %>
</p>

<!--<p>
  <strong>Tax cost:</strong>
  <%# @bid.tax_cost %>
</p>-->

<p>
  <strong>Total cost:</strong>
  <%= @bid.total_cost %>
</p>

<p>
  <strong>Conditions:</strong>
  <%= @bid.conditions %>
</p>

<p>
  <strong>Cabinet mix:</strong>
  <%= @bid.cabinet_mix %>
</p>

<p>
  <strong>Cabinet ID:</strong>
  <%= @bid.cabinet_id %>
</p>

<p>
  <strong>Cabinet ID from Cabinet table:</strong>
  <%= @bid.cabinet.id %>
</p>

<p>
  <strong>Cabinet Name:</strong>
  <%= @bid.cabinet.name %>
</p>

<p>
  <strong>Cabinet specs:</strong>
  <%= @bid.cabinet.specs %>
</p>

<p>
  <strong>Granite ID:</strong>
  <%= @bid.granite_id %>
</p>

<p>
  <strong>Granite Name:</strong>
  <%= @bid.granite.name %>
</p>


<%= link_to 'Edit', edit_bid_path(@bid) %> |
<%= link_to 'Back', bids_path %>