config/routes.rb
Rails.application.routes.draw do
  root to: 'bids#index'
  
  resources :granites

  resources :cabinets

  resources :bids

end

app/models/cabinet.rb
class Cabinet < ActiveRecord::Base
  has_many :bids
  mount_uploader :image, ImageUploader
end

app/controllers/cabinets_controller.rb
class CabinetsController < ApplicationController
  before_action :set_cabinet, only: [:show, :edit, :update, :destroy]

  # GET /cabinets
  # GET /cabinets.json
  def index
    @cabinets = Cabinet.all
  end

  # GET /cabinets/1
  # GET /cabinets/1.json
  def show
  end

  # GET /cabinets/new
  def new
    @cabinet = Cabinet.new
  end

  # GET /cabinets/1/edit
  def edit
  end

  # POST /cabinets
  # POST /cabinets.json
  def create
    @cabinet = Cabinet.new(cabinet_params)

    respond_to do |format|
      if @cabinet.save
        format.html { redirect_to @cabinet, notice: 'Cabinet was successfully created.' }
        format.json { render :show, status: :created, location: @cabinet }
      else
        format.html { render :new }
        format.json { render json: @cabinet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cabinets/1
  # PATCH/PUT /cabinets/1.json
  def update
    respond_to do |format|
      if @cabinet.update(cabinet_params)
        format.html { redirect_to @cabinet, notice: 'Cabinet was successfully updated.' }
        format.json { render :show, status: :ok, location: @cabinet }
      else
        format.html { render :edit }
        format.json { render json: @cabinet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cabinets/1
  # DELETE /cabinets/1.json
  def destroy
    @cabinet.destroy
    respond_to do |format|
      format.html { redirect_to cabinets_url, notice: 'Cabinet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cabinet
      @cabinet = Cabinet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cabinet_params
      params.require(:cabinet).permit(:name, :image, :specs)
    end
end

app/helpers/cabinets_helper.rb
module CabinetsHelper
end

app/views/cabinets/_form.html.erb
<%= form_for(@cabinet) do |f| %>
  <% if @cabinet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cabinet.errors.count, "error") %> prohibited this cabinet from being saved:</h2>

      <ul>
      <% @cabinet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :specs %><br>
    <%= f.text_area :specs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cabinets/edit.html.erb
<h1>Editing cabinet</h1>

<%= render 'form' %>

<%= link_to 'Show', @cabinet %> |
<%= link_to 'Back', cabinets_path %>

app/views/cabinets/index.html.erb
<h1>Cabinet Styles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Specs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cabinets.each do |cabinet| %>
      <tr>
        <td><%= cabinet.name %></td>
        <td><%= image_tag(cabinet.image, :width => 50) if cabinet.image.present? %></td>
        <td><%= cabinet.specs %></td>
        <td><%= link_to 'Show', cabinet %></td>
        <td><%= link_to 'Edit', edit_cabinet_path(cabinet) %></td>
        <td><%= link_to 'Destroy', cabinet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cabinet Style', new_cabinet_path %>

app/views/cabinets/new.html.erb
<h1>New cabinet</h1>

<%= render 'form' %>

<%= link_to 'Back', cabinets_path %>

app/views/cabinets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cabinet.name %>
</p>

<!--<p>
  <strong>Image:</strong>
  <%= @cabinet.image %>
</p>-->

<p>
  <strong>Photo:</strong>
  <%= image_tag(@cabinet.image, :width => 200) if @cabinet.image.present? %>
</p>

<p>
  <strong>Specs:</strong>
  <%= @cabinet.specs %>
</p>

<%= link_to 'Edit', edit_cabinet_path(@cabinet) %> |
<%= link_to 'Back', cabinets_path %>